apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/namespace.yaml

  - config/configmap.yaml
  - config/secret.yaml

  - database/pvc.yaml
  - database/deployment.yaml
  - database/service.yaml

  - backend/deployment.yaml
  - backend/service.yaml

  - frontend/deployment.yaml
  - frontend/service.yaml

  - ingress/ingress.yaml