[k3s_server]
control ansible_host=52.53.3.233 private_ip=10.0.1.162 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/klassiq/.ssh/phoenix-k3s-key.pem

[k3s_workers]
worker1 ansible_host=3.101.88.154 private_ip=10.0.1.161 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/klassiq/.ssh/phoenix-k3s-key.pem
worker2 ansible_host=54.219.195.46 private_ip=10.0.1.208 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/klassiq/.ssh/phoenix-k3s-key.pem

[k3s_cluster:children]
k3s_server
k3s_workers